# Generated by Django 4.0.3 on 2023-05-07 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0002_remove_blog_like_count_blog_interaction_blog_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='author.comments'),
        ),
    ]
