version: "3.9"
services:
  app:
    build: .  
    volumes:
      - .:/ChatGPTBlogWebAppRender
    ports:
      - "8000:8000"
    
    image: django1
    container_name: django_container1
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - zemberek

  db:

    image: postgres
    container_name: postgres_container2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vural
      - POSTGRES_DB=grup_14
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container1
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"


  zemberek:
    image: ryts/zemberek-grpc
    container_name: zemberek_container1
    ports:
      - "6789:6789"

  
