# Generated by Django 4.2 on 2023-04-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/img", verbose_name="Resim"
            ),
        ),
    ]
