# Generated by Django 4.2 on 2023-04-30 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followings", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
