# Generated by Django 4.2 on 2023-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0002_alter_author_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="image",
            field=models.ImageField(upload_to="library/"),
        ),
    ]
