# Generated by Django 4.2 on 2023-04-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0004_alter_author_img_alter_blog_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(
                blank=True, null=True, upload_to="images", verbose_name="Resim"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="banner",
            field=models.ImageField(upload_to="banners"),
        ),
    ]
