# Generated by Django 4.2 on 2023-06-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="is_author",
            field=models.BooleanField(default=False),
        ),
    ]
