# Generated by Django 4.2.1 on 2023-05-21 22:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='search_post',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='stemmed_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='stemmed_tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='stemmed_title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags_full',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_post'], name='author_blog_search__53e99c_gin'),
        ),
    ]
