# Generated by Django 4.0.3 on 2023-04-27 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_draft_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draft',
            old_name='text',
            new_name='content',
        ),
    ]
