# Generated by Django 4.2.1 on 2023-05-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_blog_search_post_blog_stemmed_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tags_full',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
