# Generated by Django 4.2 on 2023-05-30 20:36

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0003_blog_favorite_comments_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="search_post",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="stemmed_author_name_surname",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="stemmed_author_user",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="stemmed_content",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="stemmed_tags",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="stemmed_title",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="tags_full",
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
        migrations.AddIndex(
            model_name="blog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_post"], name="author_blog_search__53e99c_gin"
            ),
        ),
    ]
