# Generated by Django 4.2.1 on 2023-05-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_blog_tags_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
