# Generated by Django 4.2.1 on 2023-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, unique=True),
        ),
    ]
