# Generated by Django 4.2.1 on 2023-05-31 19:33

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='author_blog_search__53e99c_gin',
        ),
        migrations.AddField(
            model_name='blog',
            name='search_author',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_post', 'search_author'], name='author_blog_search__f22647_gin'),
        ),
    ]
