# Generated by Django 4.2.1 on 2023-05-31 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('author', '0009_remove_blog_author_blog_search__53e99c_gin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_id',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='author.author'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
